#Account info write the username of all your account
account_username:
  - "a"

#Account info write the password of all your account
account_password:
  - "z"

# If headless is set to True the bot won't open a chrome windows while doing giveaways otherwise it will
headless: False